<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs before class]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs before every method]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> Method 1 running]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs after every method]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs before every method]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs after every method]]>
    </line>
    <line>
      <![CDATA[TestNG_ReporterAndLogs>>> This runs after class]]>
    </line>
  </reporter-output>
  <suite started-at="2018-03-21T14:09:07Z" name="Reporter suite" finished-at="2018-03-21T14:09:07Z" duration-ms="118">
    <groups>
    </groups>
    <test started-at="2018-03-21T14:09:07Z" name="Application Reporter log testing Test" finished-at="2018-03-21T14:09:07Z" duration-ms="118">
      <class name="testClasses.TestNG_reportersAndLogs">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="setUp" finished-at="2018-03-21T10:09:07Z" duration-ms="18" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs before class]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test1()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="test1" finished-at="2018-03-21T10:09:07Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> Method 1 running]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="beforeMethod" finished-at="2018-03-21T10:09:07Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs before every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="afterMethod" finished-at="2018-03-21T10:09:07Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs after every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="test2()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="test2" finished-at="2018-03-21T10:09:07Z" duration-ms="26" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testClasses.TestNG_reportersAndLogs.test2(TestNG_reportersAndLogs.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="beforeMethod" finished-at="2018-03-21T10:09:07Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs before every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="afterMethod" finished-at="2018-03-21T10:09:07Z" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs after every method]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="test3()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="test3" finished-at="2018-03-21T10:09:07Z" depends-on-methods="testClasses.TestNG_reportersAndLogs.test2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNG_reportersAndLogs.test3()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNG_reportersAndLogs.test3()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TestNG_reportersAndLogs@4f209819]" started-at="2018-03-21T10:09:07Z" name="tearDown" finished-at="2018-03-21T10:09:07Z" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestNG_ReporterAndLogs>>> This runs after class]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TestNG_reportersAndLogs -->
    </test> <!-- Application Reporter log testing Test -->
  </suite> <!-- Reporter suite -->
</testng-results>
