<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-03-22T20:23:30Z" name="login test suite" finished-at="2018-03-22T20:24:03Z" duration-ms="33242">
    <groups>
    </groups>
    <test started-at="2018-03-22T20:23:30Z" name="first selenium login test with id" finished-at="2018-03-22T20:24:03Z" duration-ms="33242">
      <class name="extendReports.seleniumLoginTutorial">
        <test-method is-config="true" signature="classSetup()[pri:0, instance:extendReports.seleniumLoginTutorial@43195e57]" started-at="2018-03-22T16:23:48Z" name="classSetup" finished-at="2018-03-22T16:23:54Z" duration-ms="6321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method signature="testLogin()[pri:0, instance:extendReports.seleniumLoginTutorial@43195e57]" started-at="2018-03-22T16:23:54Z" name="testLogin" finished-at="2018-03-22T16:24:03Z" duration-ms="8049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="classTearDown()[pri:0, instance:extendReports.seleniumLoginTutorial@43195e57]" started-at="2018-03-22T16:24:03Z" name="classTearDown" finished-at="2018-03-22T16:24:03Z" duration-ms="263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTearDown -->
      </class> <!-- extendReports.seleniumLoginTutorial -->
      <class name="extendReports.seleniumLoginTutorialScreenshot">
        <test-method is-config="true" signature="classSetup()[pri:0, instance:extendReports.seleniumLoginTutorialScreenshot@1ab3a8c8]" started-at="2018-03-22T16:23:30Z" name="classSetup" finished-at="2018-03-22T16:23:38Z" duration-ms="8088" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method signature="testLogin()[pri:0, instance:extendReports.seleniumLoginTutorialScreenshot@1ab3a8c8]" started-at="2018-03-22T16:23:38Z" name="testLogin" finished-at="2018-03-22T16:23:47Z" duration-ms="9143" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at extendReports.seleniumLoginTutorialScreenshot.testLogin(seleniumLoginTutorialScreenshot.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:extendReports.seleniumLoginTutorialScreenshot@1ab3a8c8]" started-at="2018-03-22T16:23:47Z" name="tearDown" finished-at="2018-03-22T16:23:48Z" duration-ms="1330" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=seleniumLoginTutorialScreenshot.testLogin()[pri:0, instance:extendReports.seleniumLoginTutorialScreenshot@1ab3a8c8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extendReports.seleniumLoginTutorialScreenshot -->
    </test> <!-- first selenium login test with id -->
  </suite> <!-- login test suite -->
</testng-results>
